// web/src/utils/categories.ts

export const OFFICIAL_CATEGORIES = [
  { key: 'ACTION', label: 'Acción' },
  { key: 'ADVENTURE', label: 'Aventura' },
  { key: 'COMEDY', label: 'Comedia' },
  { key: 'HORROR', label: 'Terror' },
  { key: 'SCI_FI', label: 'Ciencia Ficción' },
  { key: 'FANTASY', label: 'Fantasía' },
  { key: 'ROMANCE', label: 'Romance' },
  { key: 'DRAMA', label: 'Drama' },
  { key: 'ANIMATION', label: 'Animación' },
  { key: 'MUSICAL', label: 'Musical' },
  { key: 'WESTERN', label: 'Western' },
  { key: 'WAR', label: 'Bélico' },
  { key: 'THRILLER_MYSTERY', label: 'Suspenso y Misterio' },
  { key: 'CRIME_COP', label: 'Crimen y Policial' },
  { key: 'ERA_ORIGINS_SILENT', label: 'Orígenes y Cine Mudo (1895 - 1929)' },
  { key: 'ERA_CLASSIC_STUDIO', label: 'Cine Clásico (1930 - 1959)' },
  { key: 'ERA_NEW_WAVES_MODERN', label: 'Cine Moderno (1960 - 1979)' },
  { key: 'ERA_BLOCKBUSTER_POP', label: 'Era Blockbuster (1980 - 1999)' },
  { key: 'ERA_NEW_MILLENNIUM', label: 'Nuevo Milenio (2000 - 2019)' },
  { key: 'ERA_CONTEMPORARY', label: 'Cine Contemporáneo (2020+)' },
  { key: 'CINEMA_AR', label: 'Cine Argentino' },
  { key: 'CINEMA_LATAM', label: 'Cine Latinoamericano' },
  { key: 'CINEMA_EU', label: 'Cine Europeo' },
  { key: 'CINEMA_ASIAN', label: 'Cine Asiático' },
  { key: 'CAST_DIRECTORS', label: 'Actores y Directores' },
  { key: 'AWARDS_FESTIVALS', label: 'Premios y Festivales' },
  { key: 'BASED_ON_TRUE_EVENTS', label: 'Basadas en hechos reales' },
  { key: 'COMIC_BOOK_MOVIES', label: 'Basadas en cómics' },
  { key: 'LITERARY_ADAPTATIONS', label: 'Adaptaciones literarias' },
  { key: 'FRANCHISES_SAGAS', label: 'Sagas y Franquicias' },
];